// Student constants
export const STUDENT_FIRSTNAME_MIN_LENGTH = 2;
export const STUDENT_FIRSTNAME_MAX_LENGTH = 50;
export const STUDENT_LASTNAME_MIN_LENGTH = 2;
export const STUDENT_LASTNAME_MAX_LENGTH = 50;
export const STUDENT_ROLL_NO_LENGTH = 10;
export const STUDENT_PASSWORD_MIN_LENGTH = 4;

// Teacher constants
export const TEACHER_FIRSTNAME_MIN_LENGTH = 2;
export const TEACHER_FIRSTNAME_MAX_LENGTH = 50;
export const TEACHER_LASTNAME_MIN_LENGTH = 2;
export const TEACHER_LASTNAME_MAX_LENGTH = 50;
export const TEACHER_ID_LENGTH = 8;
export const TEACHER_PASSWORD_MIN_LENGTH = 4;
export const TEACHER_QUALIFICATION_MIN_LENGTH = 4;